<a href="https://colab.research.google.com/github/leenago/Projects/blob/master/Agrifood/Agrifood_%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%99%95%EC%9D%B8%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [2]:
%cd /content/gdrive/My Drive/bigdata/Projects/농식품해커톤/1. 기상정보

/content/gdrive/My Drive/bigdata/Projects/농식품해커톤/1. 기상정보

In [3]:
import pandas as pd
import numpy as np

### 1. 농진청 기상자료

In [4]:
df = pd.read_excel('20190101_20191231_농진청 기상 일별 자료(2019-10-23).xlsx', header=1)
#column으로 만들고자 하는 행의 자리를 header 안에 넣어주면 그 행이 column이 되게 된다.
df

          관측지점        조회일자  평균기온(150cm)  ...   초상온도  지중온도(10cm)  Unnamed: 16
0      가평군 가평읍  2019-01-01        -7.52  ...    NaN         NaN          NaN
1      가평군 가평읍  2019-01-02        -7.50  ...    NaN         NaN          NaN
2      가평군 가평읍  2019-01-03        -7.57  ...    NaN         NaN          NaN
3      가평군 가평읍  2019-01-04        -4.42  ...    NaN         NaN          NaN
4      가평군 가평읍  2019-01-05        -2.54  ...    NaN         NaN          NaN
...        ...         ...          ...  ...    ...         ...          ...
61880  횡성군 공근면  2019-10-18        13.00  ...  12.33         NaN          NaN
61881  횡성군 공근면  2019-10-19        12.92  ...  12.48         NaN          NaN
61882  횡성군 공근면  2019-10-20        12.26  ...  11.85         NaN          NaN
61883  횡성군 공근면  2019-10-21        13.06  ...  12.67         NaN          NaN
61884  횡성군 공근면  2019-10-22        14.00  ...  13.49         NaN          NaN

[61885 rows x 17 columns]

In [5]:
df.columns

Index(['관측지점', '조회일자', '평균기온(150cm)', '풍향', '최고기온', '풍속', '최저기온', '순간풍속',
       '습도(150cm)', '강수량', '토양수분(10cm)', '이슬지속시간', '일사량', '일조시간', '초상온도',
       '지중온도(10cm)', 'Unnamed: 16'],
      dtype='object')

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61885 entries, 0 to 61884
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   관측지점         61885 non-null  object
 1   조회일자         61885 non-null  object
 2   평균기온(150cm)  61872 non-null  float64
 3   풍향           57947 non-null  float64
 4   최고기온         61872 non-null  float64
 5   풍속           61000 non-null  float64
 6   최저기온         61872 non-null  float64
 7   순간풍속         32905 non-null  float64
 8   습도(150cm)    61444 non-null  float64
 9   강수량          61885 non-null  float64
 10  토양수분(10cm)   0 non-null      float64
 11  이슬지속시간       53766 non-null  float64
 12  일사량          58333 non-null  float64
 13  일조시간         40431 non-null  float64
 14  초상온도         36242 non-null  float64
 15  지중온도(10cm)   0 non-null      float64
 16  Unnamed: 16  0 non-null      float64
dtypes: float64(15), object(2)
memory usage: 8.0+ MB

In [25]:
rda_weather = df.drop(columns=['지중온도(10cm)','토양수분(10cm)','Unnamed: 16'])
rda_weather

          관측지점        조회일자  평균기온(150cm)      풍향  ...  이슬지속시간    일사량   일조시간   초상온도
0      가평군 가평읍  2019-01-01        -7.52  204.29  ...     0.0   0.00    0.0    NaN
1      가평군 가평읍  2019-01-02        -7.50  176.44  ...     0.0   0.00    0.0    NaN
2      가평군 가평읍  2019-01-03        -7.57  176.50  ...     0.0   0.00    0.0    NaN
3      가평군 가평읍  2019-01-04        -4.42  187.41  ...     0.0   0.00    0.0    NaN
4      가평군 가평읍  2019-01-05        -2.54  217.15  ...     0.0   0.00    0.0    NaN
...        ...         ...          ...     ...  ...     ...    ...    ...    ...
61880  횡성군 공근면  2019-10-18        13.00   64.61  ...     5.0   8.03  114.0  12.33
61881  횡성군 공근면  2019-10-19        12.92  188.09  ...   113.0  13.70  445.0  12.48
61882  횡성군 공근면  2019-10-20        12.26  258.88  ...     0.0  12.15  404.0  11.85
61883  횡성군 공근면  2019-10-21        13.06  168.23  ...   246.0  12.63  439.0  12.67
61884  횡성군 공근면  2019-10-22        14.00  194.37  ...   169.0  11.56  358.0  13.49

[61885 rows x 14 columns]

In [27]:
rda_weather['관측지점'].unique()

array(['가평군 가평읍', '강릉 안반덕이', '강릉시 연곡면', '강진군 군동면', '거제시 거제면', '거창군 거창읍',
       '거창군 동변리', '거창군 주상면', '경산시 자인면', '경주시 용강상리', '계룡시 두마면', '고성군 고성읍',
       '고양시 구산동', '고양시 덕양구', '고흥군 풍양면', '곡성군 오곡면', '공주시 우성면', '광주시 목현동',
       '구례군 구례읍', '구미시 선산읍', '구미시 옥성면', '군위군 소보면', '군위군 효령면', '금산군 금성면',
       '김제시 부량면', '김포시 월곶면', '김해시 전하동', '나주시 공산면', '나주시 금천면', '나주시 문평면',
       '나주시 봉황면', '남양주 진건읍', '남원시 운봉읍', '남원시 이백면', '남해군 이동면', '논산시 광석면',
       '당진시 당진읍', '대구시 북구', '동해시 북평동', '무안군 청계면', '무안군 현경면', '무주군 무주읍',
       '문경시 흥덕동', '밀양시 산내면', '밀양시 상남면', '보령시 주교면', '보성군 보성읍', '보성군 웅치면',
       '봉화군 봉성면', '봉화군 석포면', '봉화군 외삼리', '부산시 강서구', '부안군 계화면', '부여군 규암면',
       '사천시 송포동', '사천시 용현면', '삼척시 근덕면', '삼척시 미로면', '상주시 공성면', '상주시 외서면',
       '상주시 초산동', '상주시 화서면', '서귀포 감산리', '서귀포 남원읍', '서귀포 대정읍', '서귀포 덕수리',
       '서귀포 성산읍', '서귀포 신효동', '서귀포 신흥리', '서귀포 중문동', '서귀포 창천리', '서귀포 표선면',
       '서귀포 하례리', '서귀포 하원동', '서울시 서초구', '성주군 대가면', '성주군 대천리', '속초시 대포동',
       '수원시 서둔동', '순창군 구림면', '순천시 주암면', '시흥시 하중동', '신안군 압해읍', '아산시 염치읍',
       '안동시 북후면', '안동시 송천동', '안산시 단원구', '안산시 상록구', '안성시 보개면', '양구군 만대리',
       '양구군 후리', '양양군 손양면', '양주시 광적면', '양평군 양평읍', '여수시 주삼동', '여주시 상거동',
       '연천군 신서면', '연천군 연천읍', '영광군 군서면', '영덕군 병곡면', '영동군 심천면', '영암군 덕진면',
       '영양군 대천리', '영양군 영양읍', '영월군 영월읍', '영주시 봉현면', '영주시 부석면', '영주시 안정로',
       '영주시 안풍리', '영주시 용산리', '영주시 평은면', '영주시 풍기읍', '영천시 금호읍', '영천시 오미동',
       '예산군 신암면', '예천군 예천읍', '옥천군 옥천읍', '옹진군 백령면', '옹진군 영흥면', '완도군 완도읍',
       '완주군 고산면', '완주군 반교리', '완주군 이서면', '용인시 처인구', '울산시 청량면', '울주군 서생면',
       '울진군 매화면', '원주시 흥업면', '음성군 소이면', '의성군 봉양면', '의성군 옥산면', '의성군 의성읍',
       '이천시 장호원', '이천시 중리동', '이천시 진암리', '익산시 함열읍', '인제군 인제읍', '임실군 신평면',
       '장성군 장성읍', '장수군 개정리', '장수군 장수읍', '장흥군 장흥읍', '전남농업기술원', '정선군 신동읍',
       '정선군 임계면', '정선군 정선읍', '정읍시 정우면', '제주시 구좌읍', '제주시 금악리', '제주시 김녕리',
       '제주시 덕천리', '제주시 상귀길', '제주시 세화리', '제주시 신엄리', '제주시 애월읍', '제주시 오등동',
       '제주시 월각로', '제주시 조천읍', '제주시 한동리', '제주시 한림읍', '제천시 봉양읍', '진도군 군내면',
       '진안군 진안읍', '진주시 초전동', '진천군 진천읍', '창녕군 대지면', '창원시 대산면', '천안시 목천읍',
       '천안시 성환읍', '천안시 입장면', '철원군 근남면', '철원군 동송읍', '청도군 각북면', '청도군 구라리',
       '청도군 이서면', '청도군 화양읍', '청송군 부남면', '청송군 청송읍', '청양군 청양읍', '청원군 오창읍',
       '청주시 남일면', '춘천시 신북읍', '충주시 달천동', '충주시 산척면', '칠곡군 약목면', '태백 귀네미골',
       '태백시 매봉산', '태백시 황지동', '태안군 태안읍', '통영시 광도면', '파주시 아동동', '평창군 여만리',
       '평창군 운교리', '평창군 진부면', '평택시 오성면', '포천시 신북면', '포천시 영북면', '포항시 북구',
       '하동군 적량면', '하동군 화개면', '함평군 학교면', '합천군 용주면', '해남군 삼산면', '해남군 옥천면',
       '홍성군 홍성읍', '홍천군 자운리', '홍천군 화동리', '화성시 마도면', '화성시 봉담읍', '화순군 한천면',
       '화천군 화천읍', '횡성군 공근면'], dtype=object)

### 2. 기상청 기상자료

In [9]:
df2 = pd.read_excel('기상청 기상.xlsx', header=1)
df2

            연월일      지역 아이디 지역 이름  ... Unnamed: 20 Unnamed: 21 Unnamed: 22
0      20190117  4691000001    신안  ...         NaN         NaN         NaN
1      20190117  4715000088    김천  ...         NaN         NaN         연월일
2      20190117  4874000088    창녕  ...         NaN         NaN      지역 아이디
3      20190117  4887000000    함양  ...         NaN         NaN       지역 이름
4      20190117  4889000088    합천  ...         NaN         NaN  작물별 특성 아이디
...         ...         ...   ...  ...         ...         ...         ...
38806  20191230  2915500000    남구  ...         NaN         NaN         NaN
38807  20191230  2917000000    광주  ...         NaN         NaN         NaN
38808  20191230  2920000000   광산구  ...         NaN         NaN         NaN
38809  20191230  4122000000    평택  ...         NaN         NaN         NaN
38810  20191230  4122000000    평택  ...         NaN         NaN         NaN

[38811 rows x 23 columns]

In [11]:
df2.columns

Index(['연월일', '지역 아이디', '지역 이름', '작물별 특성 아이디', '작물 명', '작물별 특성 이름', '일 평균기온',
       '일 최고기온', '일 최저기온', '일 평균상대습도', '일 최저상대습도', '일 강수량', '일 평균풍속',
       '일 누적 일조시간', '특보 발효 여부', '특보 코드', '특보명', '생성_일', '생성_유저아이디',
       'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='object')

In [21]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38811 entries, 0 to 38810
Data columns (total 23 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   연월일          38811 non-null  int64
 1   지역 아이디       38811 non-null  int64
 2   지역 이름        38811 non-null  object
 3   작물별 특성 아이디   38811 non-null  object
 4   작물 명         38811 non-null  object
 5   작물별 특성 이름    38811 non-null  object
 6   일 평균기온       38208 non-null  float64
 7   일 최고기온       38218 non-null  float64
 8   일 최저기온       38218 non-null  float64
 9   일 평균상대습도     38178 non-null  float64
 10  일 최저상대습도     38371 non-null  float64
 11  일 강수량        38368 non-null  float64
 12  일 평균풍속       38127 non-null  float64
 13  일 누적 일조시간    20422 non-null  float64
 14  특보 발효 여부     13973 non-null  float64
 15  특보 코드        38811 non-null  object
 16  특보명          38811 non-null  object
 17  생성_일         38139 non-null  object
 18  생성_유저아이디     37460 non-null  object
 19  Unnamed: 19  0 non-null      float64
 20  Unnamed: 20  0 non-null      float64
 21  Unnamed: 21  0 non-null      float64
 22  Unnamed: 22  19 non-null     object
dtypes: float64(12), int64(2), object(9)
memory usage: 6.8+ MB

In [22]:
weather_center = df2.drop(columns=['Unnamed: 19','Unnamed: 20','Unnamed: 21','Unnamed: 22'])
weather_center

            연월일      지역 아이디 지역 이름  ...    특보명                 생성_일   생성_유저아이디
0      20190117  4691000001    신안  ...   특보없음  2019/03/05 11:22:42    ATADMIN
1      20190117  4715000088    김천  ...   특보없음  2019/03/05 11:22:42    ATADMIN
2      20190117  4874000088    창녕  ...   특보없음  2019/03/05 11:22:42    ATADMIN
3      20190117  4887000000    함양  ...   특보없음  2019/03/05 11:22:42    ATADMIN
4      20190117  4889000088    합천  ...  호우주의보  2019/03/05 11:22:42    ATADMIN
...         ...         ...   ...  ...    ...                  ...        ...
38806  20191230  2915500000    남구  ...   특보없음  2020/01/03 21:20:01  SCHEDULER
38807  20191230  2917000000    광주  ...   특보없음  2020/01/03 21:20:01  SCHEDULER
38808  20191230  2920000000   광산구  ...   특보없음  2020/01/03 21:20:01  SCHEDULER
38809  20191230  4122000000    평택  ...  한파주의보  2020/01/03 21:20:01  SCHEDULER
38810  20191230  4122000000    평택  ...  강풍주의보  2020/01/03 21:20:01  SCHEDULER

[38811 rows x 19 columns]

In [29]:
weather_center['지역 이름'].unique()

array(['신안', '김천', '창녕', '함양', '합천', '단양', '서산', '태안', '군위', '의성', '영천',
       '고령', '고흥', '해남', '무안', '함평', '완도', '남해', '제주', '서귀포', '진도', '아산',
       '예산', '고창', '나주', '문경', '의령', '강릉', '태백', '삼척', '영월', '평창', '정선',
       '춘천', '제천', '당진', '홍성', '영암', '평택', '부안', '홍천', '봉화', '괴산', '청양',
       '정읍', '영광', '안동', '청송', '영양', '부산', '김해', '청주', '중구', '서무', '유성구',
       '대덕구', '울산', '남구', '동구', '북구', '울주군', '여주', '강화군', '광산구', '광주',
       '서구', '횡성', '창원', '김제', '기장군', '사상구', '수영구', '영도구', '부산진구', '동래구',
       '해운대구', '사하구', '금정구', '강서구', '연제구', '동해', '속초', '고성', '양양', '사천',
       '고양', '화성', '수성구', '달서구', '달성군'], dtype=object)